"""
summarize_metrics.py — Use a local LLM to produce a human-readable summary of a
metrics.txt (or any Spider evaluation output) generated by gen_metrics or run.py.

Usage:
    uv run python -m scripts.ML.summarize_metrics data/experiment/2026-05-26_17-59-49/metrics.txt
    uv run python -m scripts.ML.summarize_metrics data/experiment/.../metrics.txt --model Qwen3-14B-4bit
    uv run python -m scripts.ML.summarize_metrics data/experiment/.../metrics.txt --max-tokens 512
"""

import sys
import argparse
from pathlib import Path

from mlx_lm import load
from mlx_lm.generate import batch_generate
from mlx_lm.sample_utils import make_sampler

from scripts.util.llm import _resolve_model_entry

DEFAULT_MODEL = "gemma-3-4b-it-4bit-DWQ"

SYSTEM_PROMPT = (
    "You are a technical assistant that extracts structured information from "
    "ML experiment logs. Reply only with a compact markdown table and nothing else."
)

USER_TEMPLATE = """\
Extract the key technical metrics from this Text-to-SQL experiment output into a single markdown table with two columns: Metric and Value. Include: model(s), config, pipeline step evaluated, difficulty, record count, execution accuracy, exact match accuracy, and any notable partial-match scores (select, where, order, group). If a metric is absent, omit its row.

<experiment_output>
{content}
</experiment_output>
"""


def main():
    parser = argparse.ArgumentParser(
        description="Summarize a metrics.txt file using a local LLM."
    )
    parser.add_argument("metrics_file", help="Path to the metrics.txt file to summarize.")
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help=f"Model key from models.json (default: {DEFAULT_MODEL}).")
    parser.add_argument("--max-tokens", type=int, default=400,
                        help="Maximum tokens to generate (default: 400).")
    args = parser.parse_args()

    metrics_path = Path(args.metrics_file)
    if not metrics_path.exists():
        print(f"Error: file not found: {metrics_path}", file=sys.stderr)
        sys.exit(1)

    content = metrics_path.read_text(encoding="utf-8").strip()

    entry = _resolve_model_entry(args.model)
    model_path = entry["path"]
    load_kwargs = {k: v for k, v in entry.items() if k != "path"}

    print(f"Loading model: {model_path}", file=sys.stderr)
    model, tokenizer = load(model_path, **load_kwargs)
    print("Model loaded.", file=sys.stderr)

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user",   "content": USER_TEMPLATE.format(content=content)},
    ]
    prompt = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        enable_thinking=False,
    )

    result = batch_generate(
        model, tokenizer, [prompt],
        max_tokens=args.max_tokens,
        verbose=False,
        sampler=make_sampler(temp=0.0),
    )

    print()
    print(result.texts[0].strip())
    print()


if __name__ == "__main__":
    main()
